# Generated by Django 6.0.1 on 2026-02-05 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0002_cartitem_color_cartitem_size'),
        ('store', '0002_variation'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='varitions',
            field=models.ManyToManyField(blank=True, to='store.variation'),
        ),
    ]
